# elastic:
#   image: elasticsearch
#   ports:
#     - 9200:9200
# imageproxy:
#   image: willnorris/imageproxy
#   ports:
#     - 8080:8080
api:
  build: .
  links:
    - mysql
    # - elastic
  ports:
    - 80:80
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /etc/resolv.conf:/etc/resolv.conf:ro
    - ./ui:/var/www/html
    - ./admin/dist:/var/www/html/admin
    - ./api:/var/www/html/api
mysql:
  image: mysql:latest
  environment:
    MYSQL_ROOT_PASSWORD: letmeindude
  ports:
    - 3306:3306
